// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Info struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Age              *int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}

func (m *Info) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Info) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

type User struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Time             *int64  `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	IsNice           *bool   `protobuf:"varint,3,req,name=isNice" json:"isNice,omitempty"`
	Info             *Info   `protobuf:"bytes,4,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *User) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *User) GetIsNice() bool {
	if m != nil && m.IsNice != nil {
		return *m.IsNice
	}
	return false
}

func (m *User) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
}
